﻿services:
  - type: web
    name: pizzeria-pedidos
    env: docker
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: PORTT
        value: "8000"

  - type: web
    name: pizzeria-entregas
    env: docker
    branch: main
    dockerfilePath: Dockerfile.entregas
    envVars:
      - key: PORT
        value: "8001"

